// Generated by CoffeeScript 1.8.0
(function() {
  var del, gulp, mainBowerFiles, minifyCss, plugins, rename, runSequence, uglify;

  gulp = require('gulp');

  del = require('del');

  uglify = require('gulp-uglify');

  minifyCss = require('gulp-minify-css');

  runSequence = require('run-sequence');

  mainBowerFiles = require('main-bower-files');

  rename = require('gulp-rename');

  plugins = require("gulp-load-plugins")({
    pattern: ["gulp-*", "gulp.*", "main-bower-files"],
    replaceString: /\bgulp[\-.]/
  });

  gulp.task('copy-libs:js', function() {
    return gulp.src(plugins.mainBowerFiles()).pipe(plugins.filter('*.js')).pipe(gulp.dest('js/'));
  });

  gulp.task('copy-libs:css', function() {
    return gulp.src(plugins.mainBowerFiles()).pipe(plugins.filter('*.css')).pipe(gulp.dest('css/'));
  });

  gulp.task('minify:js', function() {
    return gulp.src(['js/*.js', '!js/*.min.js']).pipe(rename({
      suffix: '.min'
    })).pipe(uglify()).pipe(gulp.dest('js/'));
  });

  gulp.task('minify:css', function() {
    return gulp.src(['css/*.css', '!css/*.min.css']).pipe(rename({
      suffix: '.min'
    })).pipe(minifyCss()).pipe(gulp.dest('css/'));
  });

  gulp.task('clean:js', function(cb) {
    return del(["js/*.js", "!js/*.min.js"], cb);
  });

  gulp.task('clean:css', function(cb) {
    return del(["css/*.css", "!css/*.min.css"], cb);
  });

  gulp.task('clean:all', function(cb) {
    return del(["js/", "css/"], cb);
  });

  gulp.task('copy-libs', ['copy-libs:js', 'copy-libs:css']);

  gulp.task('minify', ['minify:js', 'minify:css']);

  gulp.task('clean', ['clean:js', 'clean:css']);

  gulp.task('default', function() {
    return console.log('no-op default task');
  });

  gulp.task('build', function() {
    return runSequence('copy-libs', 'minify', 'clean');
  });

}).call(this);
