// Generated by CoffeeScript 1.8.0
(function() {
  var cssSelector, del, destDest, gulp, jsSelector, mainBowerFiles, minifyCss, plugins, rename, runSequence, srcDest, uglify;

  gulp = require('gulp');

  del = require('del');

  uglify = require('gulp-uglify');

  minifyCss = require('gulp-minify-css');

  runSequence = require('run-sequence');

  mainBowerFiles = require('main-bower-files');

  rename = require('gulp-rename');

  plugins = require("gulp-load-plugins")({
    pattern: ["gulp-*", "gulp.*", "main-bower-files"],
    replaceString: /\bgulp[\-.]/
  });

  srcDest = "src/";

  jsSelector = [srcDest + 'js/*.js', '!' + srcDest + 'js/*.min.js'];

  cssSelector = [srcDest + 'css/*.css', '!' + srcDest + 'css/*.min.css'];

  destDest = "dist/";

  gulp.task('copy-libs:js', function() {
    return gulp.src(plugins.mainBowerFiles()).pipe(plugins.filter('*.js')).pipe(gulp.dest(srcDest + 'js/'));
  });

  gulp.task('copy-libs:css', function() {
    return gulp.src(plugins.mainBowerFiles()).pipe(plugins.filter('*.css')).pipe(gulp.dest(srcDest + 'css/'));
  });

  gulp.task('minify:js', function() {
    return gulp.src(jsSelector).pipe(rename({
      suffix: '.min'
    })).pipe(uglify()).pipe(gulp.dest(srcDest + 'js/'));
  });

  gulp.task('minify:css', function() {
    return gulp.src(cssSelector).pipe(rename({
      suffix: '.min'
    })).pipe(minifyCss()).pipe(gulp.dest(srcDest + 'css/'));
  });

  gulp.task('release', function() {
    return gulp.src([srcDest + '**/*']).pipe(gulp.dest(destDest));
  });

  gulp.task('clean:js', function(cb) {
    return del(jsSelector, cb);
  });

  gulp.task('clean:css', function(cb) {
    return del(cssSelector, cb);
  });

  gulp.task('clean:all', function(cb) {
    return del([srcDest + "js/", srcDest + "css/"], cb);
  });

  gulp.task('copy-libs', ['copy-libs:js', 'copy-libs:css']);

  gulp.task('minify', ['minify:js', 'minify:css']);

  gulp.task('clean', ['clean:js', 'clean:css']);

  gulp.task('default', function() {
    return console.log('no-op default task');
  });

  gulp.task('build', function() {
    return runSequence('copy-libs', 'minify', 'clean');
  });

}).call(this);
